services:
  investorchatservice:
    image: ${DOCKER_REGISTRY-}investorchatservice
    build:
      context: .
      dockerfile: InvestorChatService/Dockerfile
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: investorchatservice-db
    environment:
      MYSQL_ROOT_PASSWORD: mysql-pw
      MYSQL_DATABASE: investorchatservice_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: